### ISSUE TITLE
hugo untar extracts hugo executable directly without creating a directory

### ISSUE THREAD

**Issue by Cuneytt** [kumorilabs/getting-to-know-k8s#1]
Untarring hugo tar does not create a directory, just extracts hugo executable.
The modified steps for hugo installation:
```
export HUGO_VERSION="0.27.1"
wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
tar -xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
sudo chmod +x hugo
sudo mv hugo /usr/local/bin/hugo
rm  hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
```

**Comment by smesch** [comment]
@Cuneytt Thanks for pointing that issue out, I have updated the docs/local-environment.md document. It was already correct in the scripts/provision-vagrant.sh script.
