### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by crisarceramos** [kumorilabs/getting-to-know-k8s#2]
Wanted to say a BIG thanks for this tutorial. Just want to ask if I can use the Jenkins setup here for Production? I wanted to use the template and probably wrap them all in one script. It makes it convenient to setup Jenkins. i'm still in progress following the steps. just want to check if this setup will also create on-demand slaves right? and that the jenkins data persist even if i destroyed the master?
TIA -cris

**Comment by smesch** [comment]
@crisarceramos Glad to hear that the labs were helpful. Regarding using the Jenkins configuration in production, if you are deploying a new cluster from scratch, you may want to consider a Highly Available (HA) setup with multiple masters spread across different availability zones: [https://github.com/kubernetes/kops/blob/master/docs/high_availability.md#high-availability-ha](url)

You are correct, Jenkins will automatically launch Pods in Kubernetes with Jenkins slaves as needed. 

And the configuration for Jenkins is backed by an AWS EBS persistent volume, so it will survive a Pod/Node failure. Deleting the entire cluster with Kops will destroy the volume though, so you would need to migrate that data away before doing so.
